const FETCH_DASHBOARDS_REQUEST = 'FETCH_DASHBOARDS';
const FETCH_DASHBOARDS_SUCCESS = 'FETCH_DASHBOARDS_SUCCESS';
const FETCH_DASHBOARDS_FAILURE = 'FETCH_DASHBOARDS_FAILURE';

export {
  FETCH_DASHBOARDS_REQUEST, FETCH_DASHBOARDS_SUCCESS, FETCH_DASHBOARDS_FAILURE,
};
