const FETCH_DASHBOARD_REQUEST = 'FETCH_DASHBOARDS_REQUEST';
const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARDS_SUCCESS';
const FETCH_DASHBOARD_FAILURE = 'FETCH_DASHBOARDS_FAILURE';

export {
  FETCH_DASHBOARD_REQUEST, FETCH_DASHBOARD_SUCCESS, FETCH_DASHBOARD_FAILURE,
};
