const FETCH_INDICATORS_REQUEST = 'FETCH_INDICATORS';
const FETCH_INDICATORS_SUCCESS = 'FETCH_INDICATORS_SUCCESS';
const FETCH_INDICATORS_FAILURE = 'FETCH_INDICATORS_FAILURE';
const CREATE_INDICATORS_REQUEST = 'CREATE_INDICATORS_REQUEST';
const CREATE_INDICATORS_SUCCESS = 'CREATE_INDICATORS_SUCCESS';
const CREATE_INDICATORS_FAILURE = 'CREATE_INDICATORS_FAILURE';
const CHANGE_FILTER = 'CHANGE_FILTER';

export {
  FETCH_INDICATORS_REQUEST, FETCH_INDICATORS_SUCCESS, FETCH_INDICATORS_FAILURE, CHANGE_FILTER,
  CREATE_INDICATORS_REQUEST, CREATE_INDICATORS_SUCCESS, CREATE_INDICATORS_FAILURE,
};
