const FETCH_INDICATORS_REQUEST = 'FETCH_INDICATORS';
const FETCH_INDICATORS_SUCCESS = 'FETCH_INDICATORS_SUCCESS';
const FETCH_INDICATORS_FAILURE = 'FETCH_INDICATORS_FAILURE';
const CHANGE_FILTER = 'CHANGE_FILTER';

export {
  FETCH_INDICATORS_REQUEST, FETCH_INDICATORS_SUCCESS, FETCH_INDICATORS_FAILURE, CHANGE_FILTER,
};
