
const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
const ADD_USER_SUCCESS= 'ADD_USER_SUCCESS';
const FORM_SUBMITION= 'FORM_SUBMITION';
const LOGIN_FAILURE= 'LOGIN_FAILURE';

export {LOGIN_SUCCESS, ADD_USER_SUCCESS, FORM_SUBMITION, LOGIN_FAILURE}
