const FETCH_MEASURES_REQUEST = 'FETCH_MEASURES';
const FETCH_MEASURES_SUCCESS = 'FETCH_MEASURES_SUCCESS';
const FETCH_MEASURES_FAILURE = 'FETCH_MEASURES_FAILURE';
const CREATE_MEASURES_REQUEST = 'CREATE_MEASURES_REQUEST';
const CREATE_MEASURES_SUCCESS = 'CREATE_MEASURES_SUCCESS';
const CREATE_MEASURES_FAILURE = 'CREATE_MEASURES_FAILURE';

export {
  FETCH_MEASURES_REQUEST, FETCH_MEASURES_SUCCESS, FETCH_MEASURES_FAILURE, 
  CREATE_MEASURES_REQUEST, CREATE_MEASURES_SUCCESS, CREATE_MEASURES_FAILURE
};
